<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\PathResolveReact\Component;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class ReactPathResolveAnonymousComponent extends RenderableComponent {
    /**
     * @var ReactPathResolveAnonymousComponent $_mod
     */
    private static $_mod;
    public static function getInstance(): ReactPathResolveAnonymousComponent {
        if (!self::$_mod) {
            self::$_mod = new ReactPathResolveAnonymousComponent();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render([], ["foo"]);
    }
}
