<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class CyclicDepsEntryModule extends CJSModule {
    /**
     * @var CyclicDepsEntryModule $_mod
     */
    private static $_mod;
    public static function getInstance(): CyclicDepsEntryModule {
        if (!self::$_mod) {
            self::$_mod = new CyclicDepsEntryModule();
        }
        return self::$_mod;
    }

    private function __construct() {
        \specimens\components\CyclicDeps\Entry1Module::getInstance()->getCyclicEntry1();
        \specimens\components\CyclicDeps\Entry2Module::getInstance()->getCyclicEntry2();
        \specimens\components\CyclicDeps\Entry2Module::getInstance()->getCyclicEntry3();
    }
}
