<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ImportResolve2Module extends CJSModule {
    /**
     * @var ImportResolve2Module $_mod
     */
    private static $_mod;
    public static function getInstance(): ImportResolve2Module {
        if (!self::$_mod) {
            self::$_mod = new ImportResolve2Module();
        }
        return self::$_mod;
    }

    private function __construct() {
        \specimens\components\PathResolve\PathResolveModule::getInstance()->getBar();
        \specimens\components\PathResolve\TsxModule::getInstance()->getTest();
        $this->getReact();
        $this->getReact2();
    }
}
