<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ImportResolveModule extends CJSModule {
    /**
     * @var ImportResolveModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ImportResolveModule {
        if (!self::$_mod) {
            self::$_mod = new ImportResolveModule();
        }
        return self::$_mod;
    }

    /**
     * @return string
     */
    public function getReact() {
        return \specimens\components\PathResolveReact\PathResolveReactModule::getInstance()->render([], []);
    }
    /**
     * @return string
     */
    public function getReact2() {
        return \specimens\components\PathResolveReact\ComponentModule::getInstance()->render([], []);
    }

    private function __construct() {
        \specimens\components\PathResolve\PathResolveModule::getInstance()->getBar();
        \specimens\components\PathResolve\PathResolveModule::getInstance()->getFoo();
        \specimens\components\PathResolve\HelpersModule::getInstance()->getFoo();
        $this->getReact();
        $this->getReact2();
    }
}
