<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ImportResolveModule extends CJSModule {
    /**
     * @var ImportResolveModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ImportResolveModule {
        if (!self::$_mod) {
            self::$_mod = new ImportResolveModule();
        }
        return self::$_mod;
    }

    private function __construct() {
        \specimens\components\ImportsTSX\ImportsTSXModule::getInstance()->getBar();
        \specimens\components\ImportsTSX\ImportsTSXModule::getInstance()->getFoo();
        \specimens\components\ImportsTSX\HelpersModule::getInstance()->getFoo();
    }
}
