<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;

class InheritedPropsModule extends CJSModule {
    /**
     * @var InheritedPropsModule $_mod
     */
    private static $_mod;
    public static function getInstance(): InheritedPropsModule {
        if (!self::$_mod) {
            self::$_mod = new InheritedPropsModule();
        }
        return self::$_mod;
    }

    /**
     * @var mixed[] $default_props
     */
    public $default_props;

    private function __construct() {
        $this->default_props = [
            "className" => "",
            "name" => null,
            "onChange" => null,
            "checked" => null,
            "defaultChecked" => null,
            "autoFocus" => false,
            "disabled" => false,
            "children" => null,
        ];
    }
}
