<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class ReactContextSourceModule extends CJSModule {
    /**
     * @var ReactContextSourceModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ReactContextSourceModule {
        if (!self::$_mod) {
            self::$_mod = new ReactContextSourceModule();
        }
        return self::$_mod;
    }

    /**
     * @var ReactContext $Ctx1
     */
    public $Ctx1;

    private function __construct() {
        $this->Ctx1 = new \VK\Elephize\Builtins\ReactContext([
            "testVal" => 1,
        ]);
    }
}
