import { ModuleRegistry } from '../cjsModules/moduleRegistry';
import { Dict } from '../../types';
import { normalizeBasePath, normalizeFileExt } from '../../utils/pathsAndNames';
import { CommonjsExternalModule } from '../cjsModules/commonjsExternalModule';
import * as path from 'path';

export function makeBootstrap(registry: ModuleRegistry, baseDir: string, rootRelativePath: string, aliases?: Dict<string>) {
  const names: string[] = [];
  registry.forEachModule((m) => {
    if (!m.isEmpty() || m instanceof CommonjsExternalModule) {
      names.push(m.targetFileName);
    }
  });
  const deps = names.map((fn) => {
    const path = fn.replace(baseDir, '');
    const modPath = normalizeFileExt(normalizeBasePath(path, baseDir, aliases));
    return `require_once __DIR__ . "/${modPath}";`;
  });

  return `<?php
/* NOTICE: autogenerated file; Do not edit by hand */
require_once __DIR__ . "/${path.join(rootRelativePath, 'builtins.php')}";
${deps.join('\n')}

`;
}
