<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\byType;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ClassesUseInExternalModule extends CJSModule {
    /**
     * @var ClassesUseInExternalModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ClassesUseInExternalModule {
        if (!self::$_mod) {
            self::$_mod = new ClassesUseInExternalModule();
        }
        return self::$_mod;
    }

    /**
     * @var \specimens\byType\classes\ClassesClass $c
     */
    public $c;

    private function __construct() {
        $this->c = new \specimens\byType\classes\ClassesClass();
        $this->c->setter1(123);
        \VK\Elephize\Builtins\Console::log(
            $this->c->getter1() + \specimens\byType\classes\ClassesClass::MY_VAR
        );
    }
}
