<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\byType;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class LoopsModule extends CJSModule {
    /**
     * @var LoopsModule $_mod
     */
    private static $_mod;
    public static function getInstance(): LoopsModule {
        if (!self::$_mod) {
            self::$_mod = new LoopsModule();
        }
        return self::$_mod;
    }

    /**
     * @var mixed[] $obj
     */
    public $obj;
    /**
     * @var float[] $obj2
     */
    public $obj2;

    private function __construct() {
        for ($i = 0; $i < 3; $i++) {
            \VK\Elephize\Builtins\Console::log($i);
        }
        $this->obj = [
            "a" => 1,
            "b" => 2,
        ];
        foreach ($this->obj as $i => $_tmpVal) {
            if (!array_key_exists($i, $this->obj)) {
                continue;
            }
            \VK\Elephize\Builtins\Console::log($i);
        }
        $this->obj2 = [1, 2, 3];
        foreach ($this->obj2 as $j) {
            \VK\Elephize\Builtins\Console::log($j);
        }
        while (true) {
            \VK\Elephize\Builtins\Console::log("kek!");
            if ($this->obj) {
                break;
            }
        }
        do {
            \VK\Elephize\Builtins\Console::log("lol!");
            if ($this->obj) {
                break;
            }
        } while (true);
    }
}
