<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\byType;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;

class ObjectLiteralExpressionModule extends CJSModule {
    /**
     * @var ObjectLiteralExpressionModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ObjectLiteralExpressionModule {
        if (!self::$_mod) {
            self::$_mod = new ObjectLiteralExpressionModule();
        }
        return self::$_mod;
    }

    /**
     * @var mixed[] $e
     */
    public $e;

    private function __construct() {
        $this->e = [
            "a" => 123,
            "b" => 321,
            "c" => 222,
            "d" => "123",
        ];
        \VK\Elephize\Builtins\Console::log($this->e);
    }
}
