let b1 = { a: 1, b: 2 };
let d1 = b1['a'];
let d2 = b1.b;
let d3 = { a: { b: { c: 1 }}};
let d4 = d3.a.b.c.toString();
let d5 = { a: { b: { c: { d: { e: 2, f: () => 1 } } }}};
let d6 = d5?.a?.b?.c?.d?.e;
let d7 = d5?.a?.b?.c?.d?.e?.toString();
let d8 = d5?.a?.b?.c?.d?.f();
console.log(d1, d2, d4, d6, d7, d8);
