<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\BasicComponentWithProps;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class BasicComponentWithProps extends RenderableComponent {
    /**
     * @var BasicComponentWithProps $_mod
     */
    private static $_mod;
    public static function getInstance(): BasicComponentWithProps {
        if (!self::$_mod) {
            self::$_mod = new BasicComponentWithProps();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $anon_deref_1
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $anon_deref_1, array $children) {
        $cnt = (float) $anon_deref_1["count"];
        $anon_2c03773 = [$cnt];
        $count = (float) $anon_2c03773[0];
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            [],
            [
                \VK\Elephize\Builtins\IntrinsicElement::get("p")->render(
                    [],
                    [
                        "You clicked ",
                        \VK\Elephize\Builtins\IntrinsicElement::escape($count),
                        " times starting at ",
                        \VK\Elephize\Builtins\IntrinsicElement::escape($cnt),
                        ".",
                    ]
                ),
                \VK\Elephize\Builtins\IntrinsicElement::get("button")->render([], [" Click me "]),
            ]
        );
    }
}
