<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\elephize_static;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class KeywordTestComponentImportModule extends CJSModule {
    /**
     * @var KeywordTestComponentImportModule $_mod
     */
    private static $_mod;
    public static function getInstance(): KeywordTestComponentImportModule {
        if (!self::$_mod) {
            self::$_mod = new KeywordTestComponentImportModule();
        }
        return self::$_mod;
    }

    /**
     * @return string
     */
    public function KeywordTestComponentImport() {
        return \specimens\components\elephize_static\KeywordTestComponent\KeywordTestComponent::getInstance()->render(
            [],
            []
        );
    }

    private function __construct() {
    }
}
