<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class __toIgnoreModule extends CJSModule {
    /**
     * @var __toIgnoreModule $_mod
     */
    private static $_mod;
    public static function getInstance(): __toIgnoreModule {
        if (!self::$_mod) {
            self::$_mod = new __toIgnoreModule();
        }
        return self::$_mod;
    }

    /**
     * @return string
     */
    public function getSome() {
        return null;
    }

    private function __construct() {
    }
}
