<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class AllowedOnClickModule extends CJSModule {
    /**
     * @var AllowedOnClickModule $_mod
     */
    private static $_mod;
    public static function getInstance(): AllowedOnClickModule {
        if (!self::$_mod) {
            self::$_mod = new AllowedOnClickModule();
        }
        return self::$_mod;
    }

    /**
     * @var mixed[] $Listeners
     */
    public $Listeners;

    private function __construct() {
        $this->Listeners = [
            "foo" => "SomeGlobalVar.foo()",
            "bar" => "SomeGlobalVar.bar()",
        ];
    }
}
