<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class ComplexObjectFuncsModule extends CJSModule {
    /**
     * @var ComplexObjectFuncsModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ComplexObjectFuncsModule {
        if (!self::$_mod) {
            self::$_mod = new ComplexObjectFuncsModule();
        }
        return self::$_mod;
    }

    /**
     * @param bool[] $names
     * @return string
     */
    public function cls($names) {
        return implode(
            " ",
            array_filter(
                array_keys($names),
                /* anon_e8959da */ function ($name) use ($names) {
                    return $names[$name];
                }
            )
        );
    }

    private function __construct() {
    }
}
