<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;

class DefaultOperatorModule extends CJSModule {
    /**
     * @var DefaultOperatorModule $_mod
     */
    private static $_mod;
    public static function getInstance(): DefaultOperatorModule {
        if (!self::$_mod) {
            self::$_mod = new DefaultOperatorModule();
        }
        return self::$_mod;
    }

    /**
     * @var float[] $doa
     */
    public $doa;
    /**
     * @var bool $dob
     */
    public $dob;
    /**
     * @var mixed[] $doc
     */
    public $doc;
    /**
     * @var float $dod
     */
    public $dod;
    /**
     * @var float|mixed[] $doe
     */
    public $doe;

    private function __construct() {
        $this->doa = [1, 2, 3];
        $this->dob = false;
        $this->doc = $this->dob ?: [
            "a" => true,
        ];
        $this->dod = $this->doa[5] ?: count($this->doa);
        $this->doe = $this->dob ?: $this->doa[5] ?: $this->doc ?: $this->dod;
        \VK\Elephize\Builtins\Console::log($this->doc, $this->dod, $this->doe);
    }
}
