<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class TypeUnionModule extends CJSModule {
    /**
     * @var TypeUnionModule $_mod
     */
    private static $_mod;
    public static function getInstance(): TypeUnionModule {
        if (!self::$_mod) {
            self::$_mod = new TypeUnionModule();
        }
        return self::$_mod;
    }

    /**
     * @var mixed $test1
     */
    public $test1;
    /**
     * @var mixed $test2
     */
    public $test2;
    /**
     * @var mixed $test3
     */
    public $test3;
    /**
     * @var string|boolean $test4
     */
    public $test4;
    /**
     * @var string|boolean $test5
     */
    public $test5;
    /**
     * @var string|boolean $test6
     */
    public $test6;
    /**
     * @var mixed $test7
     */
    public $test7;

    private function __construct() {
        $this->test1 = 1;
        $this->test2 = 1;
        $this->test3 = 1;
        $this->test4 = "";
        $this->test5 = "";
        $this->test6 = "";
        $this->test7 = true;
        \VK\Elephize\Builtins\Console::log(
            $this->test1,
            $this->test2,
            $this->test3,
            $this->test4,
            $this->test5,
            $this->test6,
            $this->test7
        );
    }
}
