<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\TypedComponent;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class TypedComponent extends RenderableComponent {
    /**
     * @var TypedComponent $_mod
     */
    private static $_mod;
    public static function getInstance(): TypedComponent {
        if (!self::$_mod) {
            self::$_mod = new TypedComponent();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $classes = (string) $props["classes"];
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(["className" => $classes], [$children]);
    }
}
