<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\fixes\ExcessiveEscaping;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class TextContainer extends RenderableComponent {
    /**
     * @var TextContainer $_mod
     */
    private static $_mod;
    public static function getInstance(): TextContainer {
        if (!self::$_mod) {
            self::$_mod = new TextContainer();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $anon_deref_1
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $anon_deref_1, array $children) {
        $align = (string) $anon_deref_1["align"];
        $class_names = ["content-text--container"];
        if ($align) {
            array_push($class_names, "content-text--container__align-" . $align);
        }
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            ["className" => \VK\Elephize\Builtins\IntrinsicElement::escape(implode(" ", $class_names))],
            [$children]
        );
    }
}
