<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc\elephizeIgnore;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\ReactContext;

class ComponentIgnore extends RenderableComponent {
    /**
     * @var ComponentIgnore $_mod
     */
    private static $_mod;
    public static function getInstance(): ComponentIgnore {
        if (!self::$_mod) {
            self::$_mod = new ComponentIgnore();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render([], ["test"]);
    }
}
