<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\CyclicDeps;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class CyclicDepsModule extends CJSModule {
    /**
     * @var CyclicDepsModule $_mod
     */
    private static $_mod;
    public static function getInstance(): CyclicDepsModule {
        if (!self::$_mod) {
            self::$_mod = new CyclicDepsModule();
        }
        return self::$_mod;
    }

    /**
     * @return mixed
     */
    public function getIndex() {
        return \specimens\components\CyclicDeps\Entry2Module::getInstance()->getCyclicEntry3();
    }

    private function __construct() {
    }
}
