<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\CyclicDeps;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class Entry1Module extends CJSModule {
    /**
     * @var Entry1Module $_mod
     */
    private static $_mod;
    public static function getInstance(): Entry1Module {
        if (!self::$_mod) {
            self::$_mod = new Entry1Module();
        }
        return self::$_mod;
    }

    /**
     * @return mixed
     */
    public function getCyclicEntry1() {
        \specimens\components\CyclicDeps\Entry2Module::getInstance()->getCyclicEntry2();
    }

    private function __construct() {
    }
}
