<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace watchSpecimens___;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;

class ImportNewFileModule extends CJSModule {
    /**
     * @var ImportNewFileModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ImportNewFileModule {
        if (!self::$_mod) {
            self::$_mod = new ImportNewFileModule();
        }
        return self::$_mod;
    }

    /**
     * @param float $b
     * @return float
     */
    public function inftest2($b) {
        return $b + 1;
    }

    private function __construct() {
        \VK\Elephize\Builtins\Console::log($this->inftest2(1));
        \VK\Elephize\Builtins\Console::log(\watchSpecimens___\ImportNewFileToImportModule::getInstance()->inftest1(1));
    }
}
