<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\BasicComponentWithViewLogic;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class BasicComponentWithViewLogic extends RenderableComponent {
    /**
     * @var BasicComponentWithViewLogic $_mod
     */
    private static $_mod;
    public static function getInstance(): BasicComponentWithViewLogic {
        if (!self::$_mod) {
            self::$_mod = new BasicComponentWithViewLogic();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $anon_e8afc0c = [$props["count"]];
        $count = (float) $anon_e8afc0c[0];
        $sec = $props["timestampInSeconds"] % 60;
        $min = floor($props["timestampInSeconds"] / 60) % 60;
        $hr = floor($props["timestampInSeconds"] / (60 * 60)) % 24;
        $sec_str = $sec < 10 ? "0" . (string) $sec : (string) $sec;
        $min_str = $min < 10 ? "0" . (string) $min : (string) $min;
        $hr_str = $hr < 10 ? "0" . (string) $hr : (string) $hr;
        $time = $hr_str . ":" . $min_str . ":" . $sec_str;
        $keys = [$hr_str, $min_str, $sec_str];
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            [],
            [
                \VK\Elephize\Builtins\IntrinsicElement::get("p")->render(
                    [],
                    ["You clicked ", $count, " times starting at ", $props["count"], "."]
                ),
                \VK\Elephize\Builtins\IntrinsicElement::get("button")->render(
                    [],
                    [
                        $time,
                        " Click me @ ",
                        Stdlib::arrayMap1(
                            $keys,
                            /* anon_1100a5a */ function ($c) {
                                return \VK\Elephize\Builtins\IntrinsicElement::get("b")->render(["key" => "b"], [$c]);
                            }
                        ),
                        \VK\Elephize\Builtins\IntrinsicElement::get("table")->render(
                            [],
                            [
                                \VK\Elephize\Builtins\IntrinsicElement::get("tbody")->render(
                                    [],
                                    [
                                        Stdlib::arrayMap2(
                                            $props["children"],
                                            /* anon_28597c3 */ function ($row, $idx) {
                                                return \VK\Elephize\Builtins\IntrinsicElement::get("tr")->render(
                                                    ["key" => "tr" . (string) $idx],
                                                    ["test"]
                                                );
                                            }
                                        ),
                                    ]
                                ),
                            ]
                        ),
                    ]
                ),
            ]
        );
    }
}
