<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\PathResolveReact;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;
use VK\Elephize\Builtins\ReactContext;

class ComponentModule extends CJSModule {
    /**
     * @var ComponentModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ComponentModule {
        if (!self::$_mod) {
            self::$_mod = new ComponentModule();
        }
        return self::$_mod;
    }

    /**
     * @return string
     */
    public function ReactPathResolveComponent() {
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render([], ["foo"]);
    }

    private function __construct() {
    }
}
