<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\PathResolveReact;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class PathResolveReactModule extends CJSModule {
    /**
     * @var PathResolveReactModule $_mod
     */
    private static $_mod;
    public static function getInstance(): PathResolveReactModule {
        if (!self::$_mod) {
            self::$_mod = new PathResolveReactModule();
        }
        return self::$_mod;
    }

    /**
     * @return string
     */
    public function PathResolveReactComponent1() {
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            [],
            [\specimens\components\PathResolveReact\ComponentModule::getInstance()->render([], [])]
        );
    }

    private function __construct() {
    }
}
