<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\byType\enum;
use VK\Elephize\Builtins\CJSModule;

class ForcedNumberedEnumEnum extends CJSModule {
    /**
     * @var float KEK
     */
    const KEK = 45;
    /**
     * @var int LOL
     */
    const LOL = 46;
    /**
     * @var int AZAZA
     */
    const AZAZA = 47;

    private function __construct() {
    }
}
