<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace VK\Elephize\src\__tests__\specimens\byType\enum;
use VK\Elephize\Builtins\CJSModule;

class NumberedEnumEnum extends CJSModule {
    /**
     * @var int KEK
     */
    const KEK = 0;
    /**
     * @var int LOL
     */
    const LOL = 1;
    /**
     * @var int AZAZA
     */
    const AZAZA = 2;

    private function __construct() {
    }
}
