<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace VK\Elephize\src\__tests__\specimens\byType\enum;
use VK\Elephize\Builtins\CJSModule;

class ValuesBasedEnumEnum extends CJSModule {
    /**
     * @var string KEK
     */
    const KEK = "kekvalue";
    /**
     * @var string LOL
     */
    const LOL = "lolvalue";
    /**
     * @var string AZAZA
     */
    const AZAZA = "azazavalue";

    private function __construct() {
    }
}
