<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc\allowedOnClick;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\ReactContext;

class AllowedGlobalClickVar2 extends RenderableComponent {
    /**
     * @var AllowedGlobalClickVar2 $_mod
     */
    private static $_mod;
    public static function getInstance(): AllowedGlobalClickVar2 {
        if (!self::$_mod) {
            self::$_mod = new AllowedGlobalClickVar2();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $variable =
            \VK\Elephize\Builtins\Date::now() % 2
                ? \specimens\misc\AllowedOnClickModule::getInstance()->Listeners["foo"]
                : \specimens\misc\AllowedOnClickModule::getInstance()->Listeners["bar"];
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(["onClick" => $variable], ["test"]);
    }
}
