<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc\allowedOnClick;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\ReactContext;
use VK\Elephize\Builtins\ReactContextSynthetic;

class AllowedGlobalClick extends RenderableComponent {
    /**
     * @var AllowedGlobalClick $_mod
     */
    private static $_mod;
    public static function getInstance(): AllowedGlobalClick {
        if (!self::$_mod) {
            self::$_mod = new AllowedGlobalClick();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            ["onClick" => "SomeGlobalVar.test()"],
            ["test"]
        );
    }
}
