<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc\allowedOnClick;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class AllowedGlobalClickVar extends RenderableComponent {
    /**
     * @var AllowedGlobalClickVar $_mod
     */
    private static $_mod;
    public static function getInstance(): AllowedGlobalClickVar {
        if (!self::$_mod) {
            self::$_mod = new AllowedGlobalClickVar();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $variable = "SomeGlobalVar.test()";
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(["onClick" => $variable], ["test"]);
    }
}
