<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc\allowedOnClick;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class AllowedGlobalClickVar3 extends RenderableComponent {
    /**
     * @var AllowedGlobalClickVar3 $_mod
     */
    private static $_mod;
    public static function getInstance(): AllowedGlobalClickVar3 {
        if (!self::$_mod) {
            self::$_mod = new AllowedGlobalClickVar3();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $variable = "foo";
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            ["onClick" => \VK\Elephize\Builtins\IntrinsicElement::escape($variable)],
            ["test"]
        );
    }
}
