<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\TwoComponents;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\ReactContext;

class FirstComponent extends RenderableComponent {
    /**
     * @var FirstComponent $_mod
     */
    private static $_mod;
    public static function getInstance(): FirstComponent {
        if (!self::$_mod) {
            self::$_mod = new FirstComponent();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $initial_props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $initial_props, array $children) {
        $props = array_merge(
            [],
            \specimens\components\TwoComponentsModule::getInstance()->default_props ?: [],
            [],
            $initial_props ?: [],
            []
        );
        $count = (float) $props["count"];
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            [],
            [
                \VK\Elephize\Builtins\IntrinsicElement::get("p")->render([], ["You clicked ", $count, " times"]),
                \VK\Elephize\Builtins\IntrinsicElement::get("button")->render([], [" Click me "]),
                \VK\Elephize\Builtins\IntrinsicElement::get("button")->render(["disabled" => true], [" Click me "]),
            ]
        );
    }
}
