<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\objectMethods;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ValuesModule extends CJSModule {
    /**
     * @var ValuesModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ValuesModule {
        if (!self::$_mod) {
            self::$_mod = new ValuesModule();
        }
        return self::$_mod;
    }

    /**
     * @var mixed[] $ok
     */
    public $ok;
    /**
     * @var mixed $okvals
     */
    public $okvals;

    private function __construct() {
        $this->ok = [
            1 => 123,
            "test" => 321,
            23 => 1111,
        ];
        $this->okvals = array_values($this->ok);
        \VK\Elephize\Builtins\Console::log($this->okvals);
    }
}
