<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace \specimens\components\NullReturnInComponent;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class NullReturnInComponent extends RenderableComponent {
    /**
     * @var NullReturnInComponent $_mod
     */
    private static $_mod;
    public static function getInstance(): NullReturnInComponent {
        if (!self::$_mod) {
            self::$_mod = new NullReturnInComponent();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param array $props
     * @param array $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        if ($props["count"] % 2) {
            return null;
        }
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            [],
            [
                \VK\Elephize\Builtins\IntrinsicElement::get("p")->render(
                    [],
                    ["You clicked ", $props["count"], " times"]
                ),
                \VK\Elephize\Builtins\IntrinsicElement::get("button")->render([], [" Click me "]),
            ]
        );
    }
}
