<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\NestedConditionalComponent;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class ComponentWrapper extends RenderableComponent {
    /**
     * @var ComponentWrapper $_mod
     */
    private static $_mod;
    public static function getInstance(): ComponentWrapper {
        if (!self::$_mod) {
            self::$_mod = new ComponentWrapper();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $other = Stdlib::objectOmit($props, ["children"]);
        return \specimens\components\DummyComponent\DummyComponent::getInstance()->render($other, [
            $children,
        ]);
    }
}
