<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\ReactSupport2;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class ReactSupport2 extends RenderableComponent {
    /**
     * @var ReactSupport2 $_mod
     */
    private static $_mod;
    public static function getInstance(): ReactSupport2 {
        if (!self::$_mod) {
            self::$_mod = new ReactSupport2();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $anon_18b93da = [1];
        $cnt = (float) $anon_18b93da[0];
        \VK\Elephize\Builtins\Console::log($cnt);
        \VK\Elephize\Builtins\Console::log($theme);
        $anon_2e8ff8c = [[1, 2, 3, 4]];
        $state = (array) $anon_2e8ff8c[0];
        \VK\Elephize\Builtins\Console::log($state);
        $memoized_callback();
        $memoized = /* anon_963ad35 */ (function () {
            return /* anon_1593e1b */ function () {
                    return "kek";
                };
        })();
        \VK\Elephize\Builtins\Console::log($memoized());
        $anon_4d3cd82 = [
            /* anon_0b7384f */ (function () {
                return /* anon_296ab44 */ function () {
                        return "kek2";
                    };
            })(),
            /* anon_f2bcb47 */ (function () {
                return /* anon_ae0fa52 */ function () {
                        return "kek3";
                    };
            })(),
        ];
        $memoized2 = $anon_4d3cd82[0];
        $memoized3 = $anon_4d3cd82[1];
        \VK\Elephize\Builtins\Console::log($memoized2(), $memoized3());
        $ref = ["current" => null];
        \VK\Elephize\Builtins\Console::log($ref["current"]);
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render([], []);
    }
}
