<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\misc\toReplaceIndex;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ToReplaceSecondCjsWrapper extends CJSModule {
    /**
     * @var \specimens\ToReplaceSecond $_impl
     */
    private $_impl;

    /**
     * @var ToReplaceSecondCjsWrapper $_mod
     */
    private static $_mod;

    public static function getInstance(): ToReplaceSecondCjsWrapper {
        if (!self::$_mod) {
            self::$_mod = new ToReplaceSecondCjsWrapper();
        }
        return self::$_mod;
    }

    /**
     * @param string $test
     * @return string
     */
    public function getFoo($test) {
        return $this->_impl->getFoo($test);
    }

    /**
     * @param string $test
     * @return string
     */
    public function getBar($test) {
        return \specimens\ToReplaceSecond::getBar($test);
    }

    private function __construct() {
        $this->_impl = new \specimens\ToReplaceSecond();
    }
}
