<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\PathResolveReact\index;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;

class PathResolveReactComponent1 extends RenderableComponent {
    /**
     * @var PathResolveReactComponent1 $_mod
     */
    private static $_mod;
    public static function getInstance(): PathResolveReactComponent1 {
        if (!self::$_mod) {
            self::$_mod = new PathResolveReactComponent1();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $_
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $_, array $children) {
        return \VK\Elephize\Builtins\IntrinsicElement::get("div")->render(
            [],
            [\specimens\components\PathResolveReact\Component\PathResolveReactComponent2::getInstance()->render([], [])]
        );
    }
}
