<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace \specimens\misc\__toIgnoreFolder;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class ToIgnoreModule extends CJSModule {
    /**
     * @var ToIgnoreModule $_mod
     */
    private static $_mod;
    public static function getInstance(): ToIgnoreModule {
        if (!self::$_mod) {
            self::$_mod = new ToIgnoreModule();
        }
        return self::$_mod;
    }

    /**
     * @return string
     */
    public function getSome2() {
        return null;
    }

    private function __construct() {
    }
}
