<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\byType\classes;
use VK\Elephize\Builtins\CJSModule;

class ClassesClass extends CJSModule {
    /**
     * @var float MY_VAR
     */
    const MY_VAR = 3;
    /**
     * @var float $prop
     */
    public $prop;
    /**
     * @var float $prop2
     */
    protected $prop2;
    /**
     * @var float $prop3
     */
    private $prop3;
    /**
     * @return float
     */
    public function getter1() {
        return $this->prop;
    }
    /**
     * @return float
     */
    protected function getter2() {
        return $this->prop2 + ClassesClass::MY_VAR;
    }
    /**
     * @return float
     */
    private function getter3() {
        return $this->prop3;
    }
    /**
     * @param float $val
     * @return mixed
     */
    public function setter1($val) {
        $this->prop3 = $val;
        return $this;
    }

    private function __construct() {
    }
}
