<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\components\ReactContextProvider;
use VK\Elephize\Builtins\RenderableComponent;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\ReactContext;

class ReactContextProvider extends RenderableComponent {
    /**
     * @var ReactContextProvider $_mod
     */
    private static $_mod;
    public static function getInstance(): ReactContextProvider {
        if (!self::$_mod) {
            self::$_mod = new ReactContextProvider();
        }
        return self::$_mod;
    }

    private function __construct() {
    }

    /**
     * @param mixed[] $props
     * @param mixed[] $children
     * @return ?string
     */
    public function render(array $props, array $children) {
        $Ctx2 = \VK\Elephize\Builtins\ReactContext::createWithDefault([
            "testInnerVal" => 2,
        ]);
        return \VK\Elephize\Builtins\ReactContext::render([
            \VK\Elephize\Builtins\ReactContext::pushContext($Ctx2, [
                "testInnerVal" => 3,
            ]),
            \VK\Elephize\Builtins\ReactContext::render([
                \VK\Elephize\Builtins\ReactContext::pushContext(
                    \specimens\components\ReactContextSourceModule::getInstance()->Ctx1,
                    [
                        "testVal" => 4,
                    ]
                ),
                \specimens\components\ReactContextConsumer\ReactContextConsumer::getInstance()->render(
                    ["someprop" => 123, "innerctx" => $Ctx2],
                    []
                ),
                \VK\Elephize\Builtins\ReactContext::popContext(
                    \specimens\components\ReactContextSourceModule::getInstance()->Ctx1
                ),
            ]),
            \VK\Elephize\Builtins\ReactContext::popContext($Ctx2),
        ]);
    }
}
