<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace specimens\fixes;
use VK\Elephize\Builtins\Stdlib;
use VK\Elephize\Builtins\CJSModule;

class EscapeHtmlCharsModule extends CJSModule {
    /**
     * @var EscapeHtmlCharsModule $_mod
     */
    private static $_mod;
    public static function getInstance(): EscapeHtmlCharsModule {
        if (!self::$_mod) {
            self::$_mod = new EscapeHtmlCharsModule();
        }
        return self::$_mod;
    }

    /**
     * @var string $armenian
     */
    public $armenian;
    /**
     * @var string $injection
     */
    public $injection;

    private function __construct() {
        $this->armenian = "&#1345;&#1381;&#1408;";
        $this->injection = "<img src=x onerror=alert()>";
    }
}
